image: debian:bookworm

stages:
  - validate

before_script:
  - apt-get -y update
  - apt-get -y install git python3-venv python3-dev python3-pip curl
  - python3 -m venv .venv && source .venv/bin/activate
  - pip3 install -r ./validate/requirements.txt
  # Install yq
  - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
  - chmod +x /usr/bin/yq


validate-vendor-list:
  stage: validate
  tags: ['ace-x86_64']
  script:
    - source .venv/bin/activate

    # Create histogram of vendors without logos
    - curl -L https://openhardware.antmicro.com/imported/components.json -O
    - yq '.[] | .manufacturingInfo.manufacturer.id' components.json -r > ohp-vendors-tmp.txt
    - yq '.[] | select(has("logo") == "false" or .logo == "true") | key' vendors.yaml -r > vendors-with-logo.txt
    - cat ohp-vendors-tmp.txt | sort | uniq > ohp-vendors.txt
    - cat ohp-vendors-tmp.txt | sort | uniq -c | sort -rn > ohp-vendors-histogram.txt
    - grep -v -f vendors-with-logo.txt ohp-vendors-histogram.txt | tee missing-icon-histogram.txt

    - ./validate/validate.py vendors.yaml
      --schema ./validate/vendor-list-schema.yaml
      --logos ./vendor-logos/
      --icons ./vendor-icons/
  artifacts:
    paths:
      - ohp-vendors.txt
      - ohp-vendors-histogram.txt
      - missing-icon-histogram.txt
    when: always

check-formatting:
  stage: validate
  tags: ['ace-x86_64']
  script:
    - source .venv/bin/activate
    - ./validate/format.py --verbose vendors.yaml
  allow_failure: true
